# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis-13000.c257.us-east-1-3.ec2.cloud.redislabs.com
      - REDIS_PASSWORD=password
      - REDIS_PORT=13000
    ports:
      - 8000:8000