# docker-compose.prod.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - 80:80
    environment:
      - REDIS_HOST=<host>
      - REDIS_PASSWORD=<password>
      - REDIS_PORT=13000
    depends_on:
      - db
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - postgres_data_prod:/var/lib/postgresql/data/
  #   expose:
  #     - 5432
  #   environment:
  #     - POSTGRES_USER=fastapi_traefik_prod
  #     - POSTGRES_PASSWORD=fastapi_traefik_prod
  #     - POSTGRES_DB=fastapi_traefik_prod

volumes:
  postgres_data_prod: